[package]
name = "mail-service"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.1"
clap = "3.0.0-beta.5"
tokio = { version = "1.13.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
mail-service-api = { version = "*", git = "https://github.com/innexgo/mail-service-api" }
serde_json = "1.0.69"
tokio-postgres = "0.7.5"
# TODO: upgrade this when a stable package comes out
aws-sdk-sesv2 = { git = "https://github.com/awslabs/aws-sdk-rust", package = "aws-sdk-sesv2" }
aws-types = { git = "https://github.com/awslabs/aws-sdk-rust", package = "aws-types" }
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", package = "aws-config" }
