[package]
name = "mail-service"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "^0.25", features = ["bundled"] }
warp ="^0.3"
clap = "3.0.0-beta.2"
tokio = { version = "1", features=["full"] }
serde = { version = "1.0", features = ["derive"] }
mail-service-api = { version = "*", git = "https://github.com/innexgo/mail-service-api" }
serde_json = "1.0.64"
rusoto_ses = "0.46.0"
rusoto_core = "0.46.0"
