[package]
name = "mail-service"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.3.2"
clap = { version = "3.0.10", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.133", features = ["derive"] }
mail-service-api = { version = "*", git = "https://github.com/innexgo/mail-service-api" }
serde_json = "1.0.75"
tokio-postgres = "0.7.5"
# TODO: upgrade this when a stable package comes out
aws-sdk-sesv2 = "0.4.1"
aws-types = "0.4.1"
aws-config = "0.4.1"
