[package]
name = "log-service"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8"
sha2 = "^0.9"
base64 = "^0.13"
rusqlite = "^0.25"
reqwest = { version = "^0.11", features=["json"]}
warp ="^0.3"
clap = "3.0.0-beta.2"
tokio = { version = "1", features=["full"] }
serde = { version = "1.0", features = ["derive"] }
log-service-api = { version = "^0.2", git = "https://github.com/innexgo/log-service-api" }
