version: "3.9"

services:
  db:
    image: postgres
    volumes:
      # Means that schema.psql will be run whenever ./data/db is not present
      # If you want to refresh the schema (and delete current data)
      # delete ./data/db
      - ./schema.psql:/docker-entrypoint-initdb.d/init.sql
      # This is a a persistent store of PSQL data for development
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=mail
    # will periodically run this command to check it hasn't crashed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  mail-service:
    build:
      dockerfile: Dev.Dockerfile
      context: .
    environment:
      - RUST_BACKTRACE=1
    command:
      [
        "/bin/mail-service",
        "--port=8080",
        "--database-url=postgres://postgres:toor@db/mail",
      ]
    ports:
      - "8080:8080"
    # waits for postgres's healthcheck to succeed before running mail-service
    depends_on:
      db:
        condition: service_healthy
